# This is a basic workflow that is manually triggered

name: workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'master'
      - 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses:actions/setup-node@v2
        with:
          node-version: '14'
      - name: install
        run: npm i -g lerna && npm run bootstrap
      - name: test
        run: npm run test:coveralls

